power_django/power/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('new/', views.post_new, name='post_new'),
    # path('<int:pk>/', views.post_detail, name='post_detail'),x    
]

power_django/power/power/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('users/', include('users.urls', namespace='users')),
]

power_django/power/users/urls.py
from django.urls import path
from users.views import login, registration, profile, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

power_django/power/favorites/models.py
from django.db import models


# from users.models import User
# from posts.models import Post
# Create your models here.


class Favorite(models.Model):
    user = models.ForeignKey('users.User', related_name='favorites', on_delete=models.CASCADE)
    post = models.ForeignKey('posts.Post', related_name='favorites', on_delete=models.CASCADE)

power_django/power/posts/models.py
from django.db import models
from users.models import User
# from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(null=False, max_length=255)
    description = models.CharField(null=False, max_length=2000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cost = models.IntegerField(null=False)
    user_id = models.ForeignKey(User,null=False,on_delete=models.RESTRICT)

    # def get_absolute_url(self):
    #     return reverse('post',kwargs={'post_id':self.pk})

    class Meta:
        verbose_name = 'Startup'
        verbose_name_plural = 'Startups'

power_django/power/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)

power_django/power/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    title = forms.CharField(label='Имена участников')
    description = forms.CharField(label='Ссылка на гуглдиск, где расписан ваш старптап')
    cost = forms.CharField(label='номер лидера команды')
    class Meta:
        model = Post
        fields = ('title', 'description','cost',)

power_django/power/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-2', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-2', 'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-2', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-2', 'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-2', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-2', 'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-2', 'placeholder': 'Подтвердите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-2', 'placeholder': ''}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-2'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-2'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control-custom w-100 p-2 border rounded '
                                                                      'bg-dark-subtle', 'readonly': True}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control-custom w-100 p-2 border rounded '
                                                                   'bg-dark-subtle', 'readonly': True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

power_django/power/favorites/views.py
from django.shortcuts import render

# Create your views here.

power_django/power/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm

def post_list(request):
    posts = Post.objects.all()
    return render(request, 'post_list.html', {'posts': posts})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if request.user.is_authenticated:
            if form.is_valid():
                title = form.data.get('title')
                description = form.data.get('description')
                cost = form.data.get('cost')
                post = Post(title=title, description=description, cost=cost, user_id_id=request.user.id)
                post.save()
                return redirect('/posts/')
    else:
        form = PostForm()
    return render(request, 'post_edit.html', {'form': form})

power_django/power/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm


def index(request):
    return render(request, 'users/base.html')


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Поздравляем! Вы успешно зарегистрированы!')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/registration.html', context)


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)
    context = {'title': 'Профиль', 'form': form}
    return render(request, 'users/profile.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

power_django/power/posts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Power</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
{% block content %}
 <div class="container m-3">
    
 </div>
{% endblock %}

 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

power_django/power/posts/templates/post_edit.html
<form method="POST" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

power_django/power/posts/templates/post_list.html
{% block content %}
 <div class="container m-3">
     <a href="/posts/new">Зарегистрироваться на конкурс</a>

    {% for post in posts %}
    <!-- <div class="post">
        <h2>{{ post.title }}</h2>
        <p>{{ post.description }}</p>
        <p>{{ post.created_at }}</p>
        <p>{{ post.updated_at }}</p>
        <p>{{ post.cost }}</p>
        <p>{{ post.user_id }}</p>
    </div> -->
{% endfor %}
 </div>
{% endblock %}

power_django/power/users/templates/users/change_password.html
{% extends 'users/base.html' %}

{% block content %}
  <h2>Change Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change Password</button>
  </form>
{% endblock %}

power_django/power/users/templates/users/login.html
{% extends 'users/base.html' %}
{% block content %}
  <div class="container">
      <div class="">
          {% if messages or form.non_field_errors %}
            <div class="alert
            {% if messages %} alert-success {% else %} alert-warning {% endif %} alert-dismissible fade show"
                 role="alert">
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% else %}
                    {{ form.non_field_errors }}
                {% endif %}
                <button type="button" class="btn-close" aria-label="Close" data-dismiss="alert"></button>
            </div>
          {% endif %}
      </div>
      <div class="w-50 mt-5 d-flex justify-content-center flex-column card">
          <h1 class="card-header">Войти в аккаунт</h1>
          <div class="card-body">
              <form action="{% url 'users:login' %}" method="post" class="">
                  {% csrf_token %}
                  <div class="form-group">
                      <label class="small mb-1" for="{{ form.username.id_for_label }}">
                          Имя пользователя
                      </label>
                      {{ form.username }}
                  </div>
                  <div class="form-group">
                      <label class="small mb-1" for="{{ form.password.id_for_label }}">
                          Пароль
                      </label>
                      {{ form.password }}
                  </div>
                  <button type="submit" class="btn btn-primary mt-3">Авторизоваться</button>
              </form>
          </div>
      </div>
  </div>
{% endblock %}

power_django/power/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block content %}
    <h2>Password Reset Successful</h2>
    <p>Your password has been successfully reset.</p>
{% endblock %}

power_django/power/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block content %}
    <h2>Enter New Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save New Password</button>
    </form>
{% endblock %}

power_django/power/users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block content %}
    <h2>Password Reset Email Sent</h2>
    <p>We have sent you an email with instructions to reset your password. Please check your inbox.</p>
{% endblock %}

power_django/power/users/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block content %}
    <h2>Reset Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset Password</button>
    </form>
{% endblock %}

power_django/power/users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/users/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="d-flex justify-content-center">
            <div class="col-lg-7">
                <h4 class="mt-3 mb-3">Профиль</h4>
                <div class="col-lg-12 text-center">
                    <img width="100" height="100"
                         src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'img/users/default-pangea.png' %} {% endif %}"
                         class="img-thumbnail">
                </div>
                <div>
                    <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                            <div class="form-group">
<!--                                <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>-->
                                {{ form.password }}
                            </div>
                        </div>

                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="border rounded p-2 mt-2">
                                    {{ form.image }}
                                    <label class="custom-file-label" for="{{ form.image.id_for_label }}">
                                        Выберите изображение
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row d-flex gap-2">
                            <div class="">
                                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                {{ form.username }}
                            </div>
                            <div class="">
                                <label class="small mb-1" for="{{ form.email.id_for_label }}">
                                    Адрес электронной почты
                                </label>
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

power_django/power/users/templates/users/registration.html
{% extends 'users/base.html' %}
{% block content %}
  <div class="container">
      <div class="w-50 mt-5 d-flex justify-content-center flex-column">
          <h1>Регистрация</h1>
          <div>
              {% if form.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert"
                     style="margin-top: 50px;">
                    {{ form.errors }}
                    <button type="button" class="btn-close" aria-label="Close" data-dismiss="alert"></button>
                </div>
              {% endif %}
          </div>
          <form action="{% url 'users:registration' %}" method="post" class="">
              {% csrf_token %}
              <div class="form-group">
                  <label class="small mb-1" for="{{ form.first_name.id_for_label }}">
                      Имя
                  </label>
                  {{ form.first_name }}
              </div>
              <div class="form-group">
                  <label class="small mb-1" for="{{ form.last_name.id_for_label }}">
                      Фамилия
                  </label>
                  {{ form.last_name }}
              </div>
              <div class="form-group">
                  <label class="small mb-1" for="{{ form.username.id_for_label }}">
                      Имя пользователя
                  </label>
                  {{ form.username }}
              </div>
              <div class="form-group">
                  <label class="small mb-1" for="{{ form.email.id_for_label }}">
                      Адрес электронной почты
                  </label>
                  {{ form.email }}
              </div>
              <div class="form-group">
                  <label class="small mb-1" for="{{ form.password1.id_for_label }}">
                      Пароль
                  </label>
                  {{ form.password1 }}
              </div>
              <div class="form-group">
                  <label class="small mb-1" for="{{ form.password2.id_for_label }}">
                      Подтверждение пароля
                  </label>
                  {{ form.password2 }}
              </div>
              <button type="submit" class="btn btn-primary mt-3">Авторизоваться</button>
          </form>
      </div>
  </div>
{% endblock %}